<a href="https://colab.research.google.com/github/LizaMilovanova/Labs/blob/main/%D0%9B%D0%A01_%D0%9C%D1%96%D0%BB%D0%BE%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D0%B0%2C_%D0%84%D0%BB%D0%B8%D0%B7%D0%B0%D0%B2%D0%B5%D1%82%D0%B0%2C_%D0%A4%D0%86%D0%A2_4_8_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Тренувальний ноутбук

**Тема:** Дії з векторами та матрицями. Бібліотека NumPy.

20 завдань. Після кожної умови залишено порожню комірку для самостійного написання коду.

У наборі використано інші числові дані, а також додано нові операції з NumPy.

## Підготовка

In [2]:
import numpy as np


## Завдання 1. Додавання, віднімання та множення векторів на число

Дано вектори:
```python
a = np.array([7, -2, 5, 9])
b = np.array([3,  6, -1, 4])
```

1. Знайдіть `a + b`.
2. Знайдіть `a - b`.
3. Помножте вектор `a` на число `4`.
4. Помножте вектор `b` на число `-2`.
5. Обчисліть поелементний добуток `a * b`.

In [4]:
# Початкові вектори
a = np.array([7, -2, 5, 9])
b = np.array([3,  6, -1, 4])

# 1. Додавання векторів
add_result = a + b

# 2. Віднімання векторів
sub_result = a - b

# 3. Множення вектора a на число 4
mul_a_scalar = a * 4

# 4. Множення вектора b на число -2
mul_b_scalar = b * -2

# 5. Поелементний добуток a * b
elem_prod = a * b

# Виведення результатів
print("1. a + b:", add_result)
print("2. a - b:", sub_result)
print("3. a * 4:", mul_a_scalar)
print("4. b * (-2):", mul_b_scalar)
print("5. a * b (поелементно):", elem_prod)

1. a + b: [10  4  4 13]
2. a - b: [ 4 -8  6  5]
3. a * 4: [28 -8 20 36]
4. b * (-2): [ -6 -12   2  -8]
5. a * b (поелементно): [ 21 -12  -5  36]


## Завдання 2. Скалярний добуток і довжина векторів

Дано вектори:
```python
u = np.array([2, -3, 6])
v = np.array([5,  1, 4])
```

1. Обчисліть скалярний добуток двома способами: `np.dot()` і оператором `@`.
2. Знайдіть евклідову норму кожного вектора.
3. Обчисліть косинус кута між векторами.

In [6]:
# Початкові вектори
u = np.array([2, -3, 6])
v = np.array([5,  1, 4])

# 1. Скалярний добуток двома способами
dot_func = np.dot(u, v)
dot_op = u @ v

# 2. Евклідова норма кожного вектора
norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)

# 3. Косинус кута між векторами: cos(θ) = (u · v) / (||u|| * ||v||)
cos_theta = dot_op / (norm_u * norm_v)

# Виведення результатів
print("1. Скалярний добуток (np.dot):", dot_func)
print("   Скалярний добуток (@):     ", dot_op)
print("2. Норма вектора u:          ", norm_u)
print("   Норма вектора v:          ", norm_v)
print("3. Косинус кута між ними:     ", cos_theta)

1. Скалярний добуток (np.dot): 31
   Скалярний добуток (@):      31
2. Норма вектора u:           7.0
   Норма вектора v:           6.48074069840786
3. Косинус кута між ними:      0.6833434069749784


## Завдання 3. Основні дії з матрицями

Дано матриці:
```python
A = np.array([
    [ 3,  5, -1],
    [ 2,  0,  4]
])

B = np.array([
    [ 1, -2,  6],
    [ 7,  3,  2]
])
```

1. Обчисліть `A + B`.
2. Обчисліть `A - B`.
3. Обчисліть поелементний добуток `A * B`.
4. Помножте матрицю `A` на число `5`.
5. Знайдіть транспоновану матрицю `A`.

In [8]:
# Початкові матриці
A = np.array([
    [ 3,  5, -1],
    [ 2,  0,  4]
])

B = np.array([
    [ 1, -2,  6],
    [ 7,  3,  2]
])

# 1. Додавання матриць
add_result = A + B

# 2. Віднімання матриць
sub_result = A - B

# 3. Поелементний добуток
elem_prod = A * B

# 4. Множення матриці A на число 5
mul_scalar = A * 5

# 5. Транспонована матриця A (використовуємо .T або np.transpose())
A_transposed = A.T

# Виведення результатів
print("1. A + B:\n", add_result)
print("\n2. A - B:\n", sub_result)
print("\n3. A * B (поелементно):\n", elem_prod)
print("\n4. A * 5:\n", mul_scalar)
print("\n5. Транспонована матриця A:\n", A_transposed)

1. A + B:
 [[4 3 5]
 [9 3 6]]

2. A - B:
 [[ 2  7 -7]
 [-5 -3  2]]

3. A * B (поелементно):
 [[  3 -10  -6]
 [ 14   0   8]]

4. A * 5:
 [[15 25 -5]
 [10  0 20]]

5. Транспонована матриця A:
 [[ 3  2]
 [ 5  0]
 [-1  4]]


## Завдання 4. Матричне множення

Дано матриці:
```python
A = np.array([
    [2, 1, 3],
    [0, 4, 5]
])

B = np.array([
    [1, 2],
    [3, 0],
    [4, 1]
])
```

1. Обчисліть матричний добуток `A @ B`.
2. Визначте форму результату.
3. Обчисліть елемент результату з індексами `[0, 1]` вручну через відповідний рядок `A` і стовпець `B` та перевірте його.

In [9]:
# Початкові матриці
A = np.array([
    [2, 1, 3],
    [0, 4, 5]
])

B = np.array([
    [1, 2],
    [3, 0],
    [4, 1]
])

# 1. Матричний добуток
C = A @ B

# 2. Форма (розмірність) результату
shape_C = C.shape

# 3. Обчислення елемента [0, 1] вручну:
# Нульовий рядок A: [2, 1, 3]
# Перший стовпець B: [2, 0, 1]
row_0_A = A[0, :]
col_1_B = B[:, 1]
manual_val = np.dot(row_0_A, col_1_B)

# Виведення результатів
print("1. Матричний добуток (A @ B):\n", C)
print("\n2. Форма результату:", shape_C)
print("\n3. Елемент [0, 1]:")
print("   - Вручну (скалярний добуток рядка 0 і стовпця 1):", manual_val)
print("   - Значення з матриці C[0, 1]:                  ", C[0, 1])
print("   - Співпадіння:                                 ", manual_val == C[0, 1])

1. Матричний добуток (A @ B):
 [[17  7]
 [32  5]]

2. Форма результату: (2, 2)

3. Елемент [0, 1]:
   - Вручну (скалярний добуток рядка 0 і стовпця 1): 7
   - Значення з матриці C[0, 1]:                   7
   - Співпадіння:                                  True


## Завдання 5. Циклічний зсув вектора

Дано вектор:
```python
v = np.array([12, 7, 19, 4, 11, 8])
```

1. Виконайте циклічний зсув на 2 позиції вправо.
2. Виконайте циклічний зсув на 3 позиції вліво.
3. Відновіть початковий вектор із результату першого зсуву.

Використайте `np.roll()`.

In [10]:
# Початковий вектор
v = np.array([12, 7, 19, 4, 11, 8])

# 1. Циклічний зсув на 2 позиції вправо (додатне значення shift)
shift_right = np.roll(v, 2)

# 2. Циклічний зсув на 3 позиції вліво (від'ємне значення shift)
shift_left = np.roll(v, -3)

# 3. Відновлення початкового вектора із shift_right (зсув назад на 2 позиції вліво)
restored_v = np.roll(shift_right, -2)

# Виведення результатів
print("Початковий вектор:               ", v)
print("1. Зсув на 2 позиції вправо:      ", shift_right)
print("2. Зсув на 3 позиції вліво:       ", shift_left)
print("3. Відновлений вектор:           ", restored_v)
print("   Перевірка (чи рівні вектори): ", np.array_equal(v, restored_v))

Початковий вектор:                [12  7 19  4 11  8]
1. Зсув на 2 позиції вправо:       [11  8 12  7 19  4]
2. Зсув на 3 позиції вліво:        [ 4 11  8 12  7 19]
3. Відновлений вектор:            [12  7 19  4 11  8]
   Перевірка (чи рівні вектори):  True


## Завдання 6. Сортування та індекси

Дано вектор:
```python
v = np.array([42, 17, 29, 8, 35, 23])
```

1. Відсортуйте елементи за зростанням.
2. Відсортуйте елементи за спаданням.
3. Отримайте індекси початкового вектора, які задають порядок елементів від найбільшого до найменшого.

Використайте `np.sort()` та `np.argsort()`.

In [11]:
# Початковий вектор
v = np.array([42, 17, 29, 8, 35, 23])

# 1. Сортування за зростанням
sorted_asc = np.sort(v)

# 2. Сортування за спаданням (розворот зрізом [::-1])
sorted_desc = np.sort(v)[::-1]

# 3. Індекси для порядку від найбільшого до найменшого
# np.argsort() сортує за зростанням, тому розгортаємо отримані індекси
desc_indices = np.argsort(v)[::-1]

# Виведення результатів
print("Початковий вектор:                    ", v)
print("1. За зростанням:                      ", sorted_asc)
print("2. За спаданням:                       ", sorted_desc)
print("3. Індекси (від більшого до меншого): ", desc_indices)
print("   Перевірка за індексами (v[indices]):", v[desc_indices])

Початковий вектор:                     [42 17 29  8 35 23]
1. За зростанням:                       [ 8 17 23 29 35 42]
2. За спаданням:                        [42 35 29 23 17  8]
3. Індекси (від більшого до меншого):  [0 4 2 5 1 3]
   Перевірка за індексами (v[indices]): [42 35 29 23 17  8]


## Завдання 7. Обмеження значень

Дано вектор:
```python
v = np.array([-12, -4, 3, 18, 27, 35, 48])
```

Обмежте всі значення діапазоном від `-5` до `30`: значення, менші за `-5`, мають стати `-5`, а більші за `30` — `30`.

Додатково визначте індекси елементів, які були змінені.

Використайте `np.clip()`.

In [12]:
# Початковий вектор
v = np.array([-12, -4, 3, 18, 27, 35, 48])

# 1. Обмеження значень діапазоном [-5, 30]
v_clipped = np.clip(v, -5, 30)

# 2. Визначення індексів змінених елементів (де початкове != обрізаному)
# np.where повертає кортеж, тому беремо перший елемент [0]
changed_indices = np.where(v != v_clipped)[0]

# Виведення результатів
print("Початковий вектор:       ", v)
print("Обмежений вектор (clip): ", v_clipped)
print("Індекси змінених значень:", changed_indices)
print("Початкові змінені числа: ", v[changed_indices])

Початковий вектор:        [-12  -4   3  18  27  35  48]
Обмежений вектор (clip):  [-5 -4  3 18 27 30 30]
Індекси змінених значень: [0 5 6]
Початкові змінені числа:  [-12  35  48]


## Завдання 8. Унікальні значення та частоти

Дано вектор:
```python
v = np.array([4, 2, 4, 7, 2, 4, 9, 7, 2, 7, 7])
```

1. Знайдіть усі унікальні значення.
2. Визначте кількість появ кожного значення.
3. Знайдіть значення, яке трапляється найчастіше.

Використайте `np.unique(..., return_counts=True)`.

In [13]:
# Початковий вектор
v = np.array([4, 2, 4, 7, 2, 4, 9, 7, 2, 7, 7])

# 1 та 2. Унікальні значення та кількість їхніх появ
unique_vals, counts = np.unique(v, return_counts=True)

# 3. Значення, яке трапляється найчастіше
# np.argmax(counts) повертає індекс максимального числа входжень
most_frequent_val = unique_vals[np.argmax(counts)]
max_count = np.max(counts)

# Виведення результатів
print("1. Унікальні значення:               ", unique_vals)
print("2. Кількість появ (частоти):         ", counts)
print(f"3. Найчастіше значення:               {most_frequent_val} (трапляється {max_count} рази)")

1. Унікальні значення:                [2 4 7 9]
2. Кількість появ (частоти):          [3 3 4 1]
3. Найчастіше значення:               7 (трапляється 4 рази)


## Завдання 9. Поворот матриці

Дано матрицю:
```python
A = np.array([
    [ 2,  4,  6,  8],
    [10, 12, 14, 16],
    [18, 20, 22, 24]
])
```

Отримайте:
1. матрицю, повернуту на 90° за годинниковою стрілкою;
2. матрицю, повернуту на 180°;
3. матрицю, повернуту на 90° проти годинникової стрілки.

Використайте `np.rot90()`.

In [14]:
# Початкова матриця
A = np.array([
    [ 2,  4,  6,  8],
    [10, 12, 14, 16],
    [18, 20, 22, 24]
])

# За замовчуванням np.rot90 повертає ПРОТИ годинникової стрілки:
# 1. Поворот на 90° за годинниковою стрілкою (k=-1 або k=3)
rot_90_cw = np.rot90(A, k=-1)

# 2. Поворот на 180° (k=2)
rot_180 = np.rot90(A, k=2)

# 3. Поворот на 90° проти годинникової стрілки (k=1)
rot_90_ccw = np.rot90(A, k=1)

# Виведення результатів
print("1. Поворот на 90° за годинниковою стрілкою:\n", rot_90_cw)
print("\n2. Поворот на 180°:\n", rot_180)
print("\n3. Поворот на 90° проти годинникової стрілки:\n", rot_90_ccw)

1. Поворот на 90° за годинниковою стрілкою:
 [[18 10  2]
 [20 12  4]
 [22 14  6]
 [24 16  8]]

2. Поворот на 180°:
 [[24 22 20 18]
 [16 14 12 10]
 [ 8  6  4  2]]

3. Поворот на 90° проти годинникової стрілки:
 [[ 8 16 24]
 [ 6 14 22]
 [ 4 12 20]
 [ 2 10 18]]


## Завдання 10. Додавання рамки до матриці

Дано матрицю:
```python
A = np.array([
    [6, 1, 8],
    [3, 5, 2],
    [9, 4, 7]
])
```

1. Додайте навколо матриці рамку шириною 1 елемент, заповнену значенням `-1`.
2. Окремо створіть рамку шириною 2 елементи, заповнену нулями.
3. Виведіть форми отриманих матриць.

Використайте `np.pad()`.

In [15]:
# Початкова матриця
A = np.array([
    [6, 1, 8],
    [3, 5, 2],
    [9, 4, 7]
])

# 1. Рамка шириною 1 елемент зі значенням -1
pad_minus_one = np.pad(A, pad_width=1, mode='constant', constant_values=-1)

# 2. Рамка шириною 2 елементи з нулями (за замовчуванням constant_values=0)
pad_zeros = np.pad(A, pad_width=2, mode='constant', constant_values=0)

# Виведення результатів та їх форм
print("1. Матриця з рамкою з -1:\n", pad_minus_one)
print("   Форма:", pad_minus_one.shape)

print("\n2. Матриця з рамкою шириною 2 з нулями:\n", pad_zeros)
print("   Форма:", pad_zeros.shape)

1. Матриця з рамкою з -1:
 [[-1 -1 -1 -1 -1]
 [-1  6  1  8 -1]
 [-1  3  5  2 -1]
 [-1  9  4  7 -1]
 [-1 -1 -1 -1 -1]]
   Форма: (5, 5)

2. Матриця з рамкою шириною 2 з нулями:
 [[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 6 1 8 0 0]
 [0 0 3 5 2 0 0]
 [0 0 9 4 7 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
   Форма: (7, 7)


## Завдання 11. Перестановка рядків і стовпців

Дано матрицю:
```python
A = np.array([
    [11, 12, 13, 14],
    [21, 22, 23, 24],
    [31, 32, 33, 34],
    [41, 42, 43, 44]
])

row_order = np.array([2, 0, 3, 1])
col_order = np.array([3, 1, 0, 2])
```

1. Переставте рядки відповідно до `row_order`.
2. Після цього переставте стовпці відповідно до `col_order`.
3. За допомогою обернених перестановок відновіть початкову матрицю.

Для побудови оберненої перестановки використайте `np.argsort()`.

In [16]:
# Початкова матриця та порядки перестановок
A = np.array([
    [11, 12, 13, 14],
    [21, 22, 23, 24],
    [31, 32, 33, 34],
    [41, 42, 43, 44]
])

row_order = np.array([2, 0, 3, 1])
col_order = np.array([3, 1, 0, 2])

# 1. Перестановка рядків
A_row_perm = A[row_order, :]

# 2. Перестановка стовпців після перестановки рядків
A_permuted = A_row_perm[:, col_order]

# 3. Відновлення початкової матриці за допомогою np.argsort()
inv_row_order = np.argsort(row_order)
inv_col_order = np.argsort(col_order)

# Відновлюємо стовпці та рядки у зворотньому порядку
A_restored = A_permuted[inv_row_order, :][:, inv_col_order]

# Виведення результатів
print("1. Матриця після перестановки рядків:\n", A_row_perm)
print("\n2. Матриця після перестановки рядків і стовпців:\n", A_permuted)
print("\n3. Відновлена матриця:\n", A_restored)
print("\nПеревірка (чи рівні матриці):", np.array_equal(A, A_restored))

1. Матриця після перестановки рядків:
 [[31 32 33 34]
 [11 12 13 14]
 [41 42 43 44]
 [21 22 23 24]]

2. Матриця після перестановки рядків і стовпців:
 [[34 32 31 33]
 [14 12 11 13]
 [44 42 41 43]
 [24 22 21 23]]

3. Відновлена матриця:
 [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]

Перевірка (чи рівні матриці): True


## Завдання 12. Трикутні частини матриці

Дано матрицю:
```python
A = np.array([
    [4, 1, 7, 2],
    [6, 3, 5, 8],
    [9, 2, 6, 1],
    [5, 7, 4, 3]
])
```

1. Отримайте верхню трикутну частину разом із головною діагоналлю.
2. Отримайте нижню трикутну частину разом із головною діагоналлю.
3. Отримайте строго верхню та строго нижню частини.
4. Відновіть початкову матрицю з нижньої та строго верхньої частин.

Використайте `np.triu()` та `np.tril()`.

In [17]:
# Початкова матриця
A = np.array([
    [4, 1, 7, 2],
    [6, 3, 5, 8],
    [9, 2, 6, 1],
    [5, 7, 4, 3]
])

# 1. Верхня трикутна частина з головною діагоналлю (k=0 за замовчуванням)
upper_tri = np.triu(A)

# 2. Нижня трикутна частина з головною діагоналлю (k=0 за замовчуванням)
lower_tri = np.tril(A)

# 3. Строго верхня (k=1) та строго нижня (k=-1) частини
strict_upper = np.triu(A, k=1)
strict_lower = np.tril(A, k=-1)

# 4. Відновлення початкової матриці (lower_tri вже містить діагональ, strict_upper — без неї)
A_restored = lower_tri + strict_upper

# Виведення результатів
print("1. Верхня трикутна частина (з діагоналлю):\n", upper_tri)
print("\n2. Нижня трикутна частина (з діагоналлю):\n", lower_tri)
print("\n3. Строго верхня частина (k=1):\n", strict_upper)
print("\n   Строго нижня частина (k=-1):\n", strict_lower)
print("\n4. Відновлена матриця (lower_tri + strict_upper):\n", A_restored)
print("\nПеревірка збігу:", np.array_equal(A, A_restored))

1. Верхня трикутна частина (з діагоналлю):
 [[4 1 7 2]
 [0 3 5 8]
 [0 0 6 1]
 [0 0 0 3]]

2. Нижня трикутна частина (з діагоналлю):
 [[4 0 0 0]
 [6 3 0 0]
 [9 2 6 0]
 [5 7 4 3]]

3. Строго верхня частина (k=1):
 [[0 1 7 2]
 [0 0 5 8]
 [0 0 0 1]
 [0 0 0 0]]

   Строго нижня частина (k=-1):
 [[0 0 0 0]
 [6 0 0 0]
 [9 2 0 0]
 [5 7 4 0]]

4. Відновлена матриця (lower_tri + strict_upper):
 [[4 1 7 2]
 [6 3 5 8]
 [9 2 6 1]
 [5 7 4 3]]

Перевірка збігу: True


## Завдання 13. Зовнішній добуток векторів

Дано вектори:
```python
a = np.array([2, 4, 7, 9])
b = np.array([3, 5, 8])
```

1. Побудуйте матрицю зовнішнього добутку.
2. Визначте її форму.
3. Перевірте, що елемент `[2, 1]` дорівнює `a[2] * b[1]`.

Використайте `np.outer()`.

In [18]:
# Початкові вектори
a = np.array([2, 4, 7, 9])
b = np.array([3, 5, 8])

# 1. Побудова матриці зовнішнього добутку
outer_matrix = np.outer(a, b)

# 2. Визначення форми матриці
shape_result = outer_matrix.shape

# 3. Перевірка елемента [2, 1]
elem_2_1 = outer_matrix[2, 1]
manual_val = a[2] * b[1]
is_equal = elem_2_1 == manual_val

# Виведення результатів
print("1. Матриця зовнішнього добутку:\n", outer_matrix)
print("\n2. Форма результату:", shape_result)
print(f"\n3. Елемент [2, 1]:")
print(f"   - Значення з матриці:  {elem_2_1}")
print(f"   - a[2] * b[1] ({a[2]} * {b[1]}): {manual_val}")
print(f"   - Рівність виконується: {is_equal}")

1. Матриця зовнішнього добутку:
 [[ 6 10 16]
 [12 20 32]
 [21 35 56]
 [27 45 72]]

2. Форма результату: (4, 3)

3. Елемент [2, 1]:
   - Значення з матриці:  35
   - a[2] * b[1] (7 * 5): 35
   - Рівність виконується: True


## Завдання 14. Добуток Кронекера

Дано матриці:
```python
A = np.array([
    [2, 1],
    [0, 3]
])

B = np.array([
    [1, 4],
    [2, 0]
])
```

1. Обчисліть добуток Кронекера `A` і `B`.
2. Обчисліть добуток Кронекера `B` і `A`.
3. Порівняйте результати та їх форми.

Використайте `np.kron()`.

In [19]:
# Початкові матриці
A = np.array([
    [2, 1],
    [0, 3]
])

B = np.array([
    [1, 4],
    [2, 0]
])

# 1. Добуток Кронекера A ⊗ B
kron_AB = np.kron(A, B)

# 2. Добуток Кронекера B ⊗ A
kron_BA = np.kron(B, A)

# 3. Порівняння результатів та їх форм
shapes_equal = kron_AB.shape == kron_BA.shape
matrices_equal = np.array_equal(kron_AB, kron_BA)

# Виведення результатів
print("1. kron(A, B):\n", kron_AB)
print("\n2. kron(B, A):\n", kron_BA)
print("\n3. Порівняння:")
print("   - Форма kron(A, B):", kron_AB.shape)
print("   - Форма kron(B, A):", kron_BA.shape)
print("   - Чи однакові форми:", shapes_equal)
print("   - Чи однакові значення (чи комутативна операція):", matrices_equal)

1. kron(A, B):
 [[ 2  8  1  4]
 [ 4  0  2  0]
 [ 0  0  3 12]
 [ 0  0  6  0]]

2. kron(B, A):
 [[ 2  1  8  4]
 [ 0  3  0 12]
 [ 4  2  0  0]
 [ 0  6  0  0]]

3. Порівняння:
   - Форма kron(A, B): (4, 4)
   - Форма kron(B, A): (4, 4)
   - Чи однакові форми: True
   - Чи однакові значення (чи комутативна операція): False


## Завдання 15. Комутатор двох матриць

Для кожної пари матриць обчисліть комутатор
\[
[A,B] = AB - BA.
\]

Перша пара:
```python
A1 = np.array([[3, 0],
               [0, 7]])
B1 = np.array([[2, 0],
               [0, 5]])
```

Друга пара:
```python
A2 = np.array([[0, 2],
               [-1, 0]])
B2 = np.array([[4, 0],
               [0, 1]])
```

Визначте, для якої пари виконується `AB = BA`. Для перевірки використайте `np.allclose()`.

In [20]:
# Перша пара матриць (діагональні)
A1 = np.array([[3, 0],
               [0, 7]])
B1 = np.array([[2, 0],
               [0, 5]])

# Друга пара матриць
A2 = np.array([[0, 2],
               [-1, 0]])
B2 = np.array([[4, 0],
               [0, 1]])

# Обчислення комутаторів: [A, B] = A @ B - B @ A
comm1 = A1 @ B1 - B1 @ A1
comm2 = A2 @ B2 - B2 @ A2

# Перевірка умови комутативності (AB = BA або [A, B] = 0)
is_comm1 = np.allclose(A1 @ B1, B1 @ A1)
is_comm2 = np.allclose(A2 @ B2, B2 @ A2)

# Виведення результатів
print("--- Перша пара ---")
print("Комутатор [A1, B1]:\n", comm1)
print("Чи комутують (A1 @ B1 == B1 @ A1):", is_comm1)

print("\n--- Друга пара ---")
print("Комутатор [A2, B2]:\n", comm2)
print("Чи комутують (A2 @ B2 == B2 @ A2):", is_comm2)

--- Перша пара ---
Комутатор [A1, B1]:
 [[0 0]
 [0 0]]
Чи комутують (A1 @ B1 == B1 @ A1): True

--- Друга пара ---
Комутатор [A2, B2]:
 [[ 0 -6]
 [-3  0]]
Чи комутують (A2 @ B2 == B2 @ A2): False


## Завдання 16. Квадратична форма

Дано симетричну матрицю:
```python
A = np.array([
    [5, 1, 0],
    [1, 4, 2],
    [0, 2, 3]
])

x = np.array([2, -1, 3])
```

1. Обчисліть квадратичну форму `xᵀAx`.
2. Для трьох векторів
```python
X = np.array([
    [ 2, -1,  3],
    [ 1,  0,  2],
    [-2,  1,  1]
])
```
обчисліть значення квадратичної форми для кожного рядка без циклу.

Для другого пункту використайте `np.einsum()`.

In [21]:
# Симетрична матриця A та вектор x
A = np.array([
    [5, 1, 0],
    [1, 4, 2],
    [0, 2, 3]
])

x = np.array([2, -1, 3])

# 1. Обчислення квадратичної форми xᵀAx
# Для одновимірного масиву в NumPy x.T еквівалентний x
quad_form_single = x @ A @ x

# 2. Обчислення для кожного рядка матриці X за допомогою np.einsum
X = np.array([
    [ 2, -1,  3],
    [ 1,  0,  2],
    [-2,  1,  1]
])

# Позначення індексів:
# i — індекс рядка матриці X
# j, k — координати у просторі розмірності 3
# 'ij,jk,ik->i' підсумовує X[i, j] * A[j, k] * X[i, k] по j та k для кожного рядка i
quad_forms_batch = np.einsum('ij,jk,ik->i', X, A, X)

# Виведення результатів
print("1. Значення xᵀAx для одного вектора:", quad_form_single)
print("2. Значення xᵀAx для кожного рядка X (np.einsum):", quad_forms_batch)

1. Значення xᵀAx для одного вектора: 35
2. Значення xᵀAx для кожного рядка X (np.einsum): [35 17 27]


## Завдання 17. Степінь матриці

Дано матрицю:
```python
A = np.array([
    [1, 1, 0],
    [0, 1, 1],
    [1, 0, 1]
])
```

1. Обчисліть `A²`.
2. Обчисліть `A³`.
3. Перевірте, що `A³ = A² @ A`.

Використайте `np.linalg.matrix_power()`.

In [22]:
# Початкова матриця
A = np.array([
    [1, 1, 0],
    [0, 1, 1],
    [1, 0, 1]
])

# 1. Обчислення A² за допомогою np.linalg.matrix_power
A2 = np.linalg.matrix_power(A, 2)

# 2. Обчислення A³
A3 = np.linalg.matrix_power(A, 3)

# 3. Перевірка рівності A³ = A² @ A
A3_check = A2 @ A
is_equal = np.array_equal(A3, A3_check)

# Виведення результатів
print("1. Матриця A²:\n", A2)
print("\n2. Матриця A³:\n", A3)
print("\n3. Перевірка A³ == A² @ A:")
print("   - Результат A² @ A:\n", A3_check)
print("   - Чи збігаються матриці:", is_equal)

1. Матриця A²:
 [[1 2 1]
 [1 1 2]
 [2 1 1]]

2. Матриця A³:
 [[2 3 3]
 [3 2 3]
 [3 3 2]]

3. Перевірка A³ == A² @ A:
   - Результат A² @ A:
 [[2 3 3]
 [3 2 3]
 [3 3 2]]
   - Чи збігаються матриці: True


## Завдання 18. Ранг матриці

Дано дві матриці:
```python
A = np.array([
    [2, 1, 0],
    [1, 3, 4],
    [0, 2, 5]
])

B = np.array([
    [1, 3, 5],
    [2, 6, 10],
    [4, 1, 0]
])
```

1. Знайдіть ранг кожної матриці.
2. Визначте, яка з них має повний ранг.

Використайте `np.linalg.matrix_rank()`.

In [23]:
# Початкові матриці
A = np.array([
    [2, 1, 0],
    [1, 3, 4],
    [0, 2, 5]
])

B = np.array([
    [1, 3, 5],
    [2, 6, 10],
    [4, 1, 0]
])

# 1. Знаходження рангу кожної матриці
rank_A = np.linalg.matrix_rank(A)
rank_B = np.linalg.matrix_rank(B)

# 2. Визначення повного рангу (для матриць 3x3 повний ранг дорівнює 3)
full_rank_A = rank_A == min(A.shape)
full_rank_B = rank_B == min(B.shape)

# Виведення результатів
print("1. Ранг матриці A:", rank_A)
print("   Ранг матриці B:", rank_B)

print("\n2. Перевірка на повний ранг:")
print(f"   - Матриця A: {'Має повний ранг' if full_rank_A else 'Не має повного рангу'}")
print(f"   - Матриця B: {'Має повний ранг' if full_rank_B else 'Не має повного рангу'}")

1. Ранг матриці A: 3
   Ранг матриці B: 2

2. Перевірка на повний ранг:
   - Матриця A: Має повний ранг
   - Матриця B: Не має повного рангу


## Завдання 19. Власні значення та власні вектори

Дано симетричну матрицю:
```python
A = np.array([
    [6.0, 2.0],
    [2.0, 3.0]
])
```

1. Знайдіть власні значення та власні вектори.
2. Перевірте співвідношення `A @ V = V * λ`.
3. Виведіть результат перевірки через `np.allclose()`.

Використайте `np.linalg.eigh()`.

In [24]:
# Початкова симетрична матриця
A = np.array([
    [6.0, 2.0],
    [2.0, 3.0]
])

# 1. Знаходження власних значень (w) та власних векторів (V)
# Функція eigh спеціалізована для симетричних/ермітових матриць
eigenvalues, V = np.linalg.eigh(A)

# 2. Перевірка співвідношення A @ V = V * λ
# Оскільки стовпці V — це власні вектори, множення V * eigenvalues
# завдяки broadcasting множить кожен стовпець j на відповідне λ[j]
lhs = A @ V
rhs = V * eigenvalues

# 3. Перевірка рівності через np.allclose()
is_valid = np.allclose(lhs, rhs)

# Виведення результатів
print("1. Власні значення (λ):", eigenvalues)
print("\n   Власні вектори (стовпці матриці V):\n", V)

print("\n2. Ліва частина (A @ V):\n", lhs)
print("\n   Права частина (V * λ):\n", rhs)

print("\n3. Співвідношення A @ V = V * λ виконується:", is_valid)

1. Власні значення (λ): [2. 7.]

   Власні вектори (стовпці матриці V):
 [[ 0.4472136  -0.89442719]
 [-0.89442719 -0.4472136 ]]

2. Ліва частина (A @ V):
 [[ 0.89442719 -6.26099034]
 [-1.78885438 -3.13049517]]

   Права частина (V * λ):
 [[ 0.89442719 -6.26099034]
 [-1.78885438 -3.13049517]]

3. Співвідношення A @ V = V * λ виконується: True


## Завдання 20. Метод найменших квадратів

Для точок
```python
x = np.array([0., 1., 2., 3., 4.])
y = np.array([2.2, 3.8, 6.1, 7.9, 10.2])
```

побудуйте пряму
\[
y \approx a + bx.
\]

1. Сформуйте матрицю ознак зі стовпця одиниць і значень `x`.
2. Знайдіть коефіцієнти `a` і `b` методом найменших квадратів.
3. Обчисліть прогнозні значення `y`.
4. Знайдіть суму квадратів залишків.

Використайте `np.linalg.lstsq()`.

In [25]:
# Початкові дані
x = np.array([0., 1., 2., 3., 4.])
y = np.array([2.2, 3.8, 6.1, 7.9, 10.2])

# 1. Формування матриці ознак: стовпець одиниць для "a" та стовпець "x" для "b"
# Можна використати np.column_stack або np.vstack([np.ones_like(x), x]).T
X_design = np.column_stack([np.ones_like(x), x])

# 2. Пошук коефіцієнтів a і b методом найменших квадратів
# np.linalg.lstsq повертає: (розв'язок, залишки, ранг, сингулярні числа)
params, residuals, rank, s = np.linalg.lstsq(X_design, y, rcond=None)
a, b = params

# 3. Обчислення прогнозних значень y
y_pred = X_design @ params  # або a + b * x

# 4. Сума квадратів залишків (Sum of Squared Residuals, SSR)
ssr = np.sum((y - y_pred) ** 2)

# Виведення результатів
print("1. Матриця ознак:\n", X_design)
print(f"\n2. Коефіцієнти прямої:")
print(f"   a (вільний член) = {a:.4f}")
print(f"   b (нахил)        = {b:.4f}")
print(f"   Рівняння прямої: y ≈ {a:.2f} + {b:.2f}x")

print("\n3. Прогнозні значення (y_pred):", np.round(y_pred, 2))
print("   Фактичні значення (y):       ", y)

print(f"\n4. Сума квадратів залишків (SSR): {ssr:.4f}")

1. Матриця ознак:
 [[1. 0.]
 [1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]]

2. Коефіцієнти прямої:
   a (вільний член) = 2.0200
   b (нахил)        = 2.0100
   Рівняння прямої: y ≈ 2.02 + 2.01x

3. Прогнозні значення (y_pred): [ 2.02  4.03  6.04  8.05 10.06]
   Фактичні значення (y):        [ 2.2  3.8  6.1  7.9 10.2]

4. Сума квадратів залишків (SSR): 0.1310
